/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/LO9zckJ31O0
 */
import { Button } from "@/components/ui/button"

export function ProjectCard() {
  return (
    (
    <div className="relative w-[350px] h-[350px] rounded-lg overflow-hidden">
      <img
        alt="Authentication app"
        className="absolute inset-0 w-full h-full object-cover"
        height="350"
        src="/placeholder.svg"
        style={{
          aspectRatio: "350/350",
          objectFit: "cover",
        }}
        width="350" />
      <div className="absolute inset-0 bg-black bg-opacity-40" />
      <h2 className="absolute top-4 left-4 text-white font-bold text-lg">Authentication app</h2>
      <Button className="absolute bottom-4 right-4 bg-white text-black">
        view project <ArrowRightIcon className="ml-2" />
      </Button>
    </div>
    )
  );
}


function ArrowRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>)
  );
}
